# app/services/storage/base.py
from __future__ import annotations

from typing import BinaryIO, Protocol


class Storage(Protocol):
    async def put(self, *, key: str, content: bytes) -> None: ...
    async def get(self, *, key: str) -> bytes: ...
    async def open(self, *, key: str) -> BinaryIO: ...
    async def delete(self, *, key: str) -> None: ...
    async def exists(self, *, key: str) -> bool: ...