"""restore tenant user email uniqueness

Revision ID: 064be53bf059
Revises: 387d2f062ccc
Create Date: 2026-09-27 08:27:41.047188

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op


revision: str = '064be53bf059'
down_revision: str | None = '387d2f062ccc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_users_tenant_email', 'users', ['tenant_id', 'email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_tenant_email', 'users', type_='unique')
    # ### end Alembic commands ###