"""auth and rbac

Revision ID: 0f326763f8e9
Revises: d3b235d9186d
Create Date: 2026-09-17 15:39:46.574015

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = '0f326763f8e9'
down_revision: str | None = 'd3b235d9186d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_tenant_email'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_users_tenant_email'), 'users', ['tenant_id', 'email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###