"""audit events and action verification

Revision ID: 194a20299539
Revises: f9ec2467ce29
Create Date: 2026-09-26 14:18:29.948300

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '194a20299539'
down_revision: str | None = 'f9ec2467ce29'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('subject_type', sa.String(length=40), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_actor_user_id'), 'audit_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_subject_id'), 'audit_events', ['subject_id'], unique=False)
    op.create_index('ix_audit_events_tenant_created', 'audit_events', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_index('ix_audit_events_tenant_type', 'audit_events', ['tenant_id', 'event_type'], unique=False)
    op.add_column('action_records', sa.Column('verification_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('action_records', sa.Column('verification_error', sa.Text(), nullable=True))
    op.add_column('action_records', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('action_records', 'verified_at')
    op.drop_column('action_records', 'verification_error')
    op.drop_column('action_records', 'verification_result')
    op.drop_index('ix_audit_events_tenant_type', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_index('ix_audit_events_tenant_created', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_subject_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_user_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###