"""data profile

Revision ID: 1b83d1dab5ef
Revises: 3587a6d217ca
Create Date: 2026-09-19 15:26:03.673953

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1b83d1dab5ef'
down_revision: Union[str, None] = '3587a6d217ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_profiles',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('profiled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('column_count', sa.Integer(), nullable=False),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('issues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['ingestion_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_profiles_job_id'), 'data_profiles', ['job_id'], unique=True)
    op.create_index(op.f('ix_data_profiles_source_id'), 'data_profiles', ['source_id'], unique=False)
    op.create_index(op.f('ix_data_profiles_tenant_id'), 'data_profiles', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_profiles_tenant_id'), table_name='data_profiles')
    op.drop_index(op.f('ix_data_profiles_source_id'), table_name='data_profiles')
    op.drop_index(op.f('ix_data_profiles_job_id'), table_name='data_profiles')
    op.drop_table('data_profiles')
    # ### end Alembic commands ###