"""row timestamps and file observations

Revision ID: 2515c7d89996
Revises: c1f13925c77a
Create Date: 2026-09-26 08:17:26.927672

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '2515c7d89996'
down_revision: str | None = 'c1f13925c77a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_observations',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=True),
    sa.Column('file_mtime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_ctime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_id', 'path', 'content_hash', name='uq_file_observations_identity')
    )
    op.create_index(op.f('ix_file_observations_source_id'), 'file_observations', ['source_id'], unique=False)
    op.create_index('ix_file_observations_source_status', 'file_observations', ['source_id', 'status'], unique=False)
    op.create_index(op.f('ix_file_observations_status'), 'file_observations', ['status'], unique=False)
    op.create_index(op.f('ix_file_observations_tenant_id'), 'file_observations', ['tenant_id'], unique=False)
    op.create_index('ix_file_observations_tenant_path', 'file_observations', ['tenant_id', 'path'], unique=False)
    op.create_table('row_timestamps',
    sa.Column('staged_row_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['staged_row_id'], ['staged_rows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staged_row_id', 'kind', name='uq_row_timestamps_row_kind')
    )
    op.create_index(op.f('ix_row_timestamps_kind'), 'row_timestamps', ['kind'], unique=False)
    op.create_index(op.f('ix_row_timestamps_staged_row_id'), 'row_timestamps', ['staged_row_id'], unique=False)
    op.create_index(op.f('ix_row_timestamps_tenant_id'), 'row_timestamps', ['tenant_id'], unique=False)
    op.create_index('ix_row_timestamps_tenant_kind_ts', 'row_timestamps', ['tenant_id', 'kind', 'timestamp'], unique=False)
    op.create_index(op.f('ix_row_timestamps_timestamp'), 'row_timestamps', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_row_timestamps_timestamp'), table_name='row_timestamps')
    op.drop_index('ix_row_timestamps_tenant_kind_ts', table_name='row_timestamps')
    op.drop_index(op.f('ix_row_timestamps_tenant_id'), table_name='row_timestamps')
    op.drop_index(op.f('ix_row_timestamps_staged_row_id'), table_name='row_timestamps')
    op.drop_index(op.f('ix_row_timestamps_kind'), table_name='row_timestamps')
    op.drop_table('row_timestamps')
    op.drop_index('ix_file_observations_tenant_path', table_name='file_observations')
    op.drop_index(op.f('ix_file_observations_tenant_id'), table_name='file_observations')
    op.drop_index(op.f('ix_file_observations_status'), table_name='file_observations')
    op.drop_index('ix_file_observations_source_status', table_name='file_observations')
    op.drop_index(op.f('ix_file_observations_source_id'), table_name='file_observations')
    op.drop_table('file_observations')
    # ### end Alembic commands ###