"""workflow triggers and events API

Revision ID: 2d89d2ef0a8b
Revises: 7db042b4c4bb
Create Date: 2026-09-26 20:27:48.923365

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2d89d2ef0a8b'
down_revision: str | None = '7db042b4c4bb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_triggers',
    sa.Column('workflow_key', sa.String(length=120), nullable=False),
    sa.Column('event_type_filter', sa.String(length=80), nullable=False),
    sa.Column('source_id_filter', sa.UUID(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('trigger_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['source_id_filter'], ['data_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'workflow_key', 'event_type_filter', 'source_id_filter', name='uq_workflow_triggers_binding')
    )
    op.create_index(op.f('ix_workflow_triggers_event_type_filter'), 'workflow_triggers', ['event_type_filter'], unique=False)
    op.create_index(op.f('ix_workflow_triggers_source_id_filter'), 'workflow_triggers', ['source_id_filter'], unique=False)
    op.create_index(op.f('ix_workflow_triggers_tenant_id'), 'workflow_triggers', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_workflow_triggers_workflow_key'), 'workflow_triggers', ['workflow_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_triggers_workflow_key'), table_name='workflow_triggers')
    op.drop_index(op.f('ix_workflow_triggers_tenant_id'), table_name='workflow_triggers')
    op.drop_index(op.f('ix_workflow_triggers_source_id_filter'), table_name='workflow_triggers')
    op.drop_index(op.f('ix_workflow_triggers_event_type_filter'), table_name='workflow_triggers')
    op.drop_table('workflow_triggers')
    # ### end Alembic commands ###