"""concept relationships and industry packs

Revision ID: 3421a29ec851
Revises: cc404502616f
Create Date: 2026-09-23 18:48:40.655394

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3421a29ec851'
down_revision: str | None = 'cc404502616f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industry_packs',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('concepts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('relationships', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('kpi_stubs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industry_packs_key'), 'industry_packs', ['key'], unique=True)
    op.create_table('concept_relationships',
    sa.Column('from_key', sa.String(length=120), nullable=False),
    sa.Column('to_key', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('cardinality', sa.String(length=10), nullable=False),
    sa.Column('join_hint', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_key'], ['canonical_concepts.key'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_key'], ['canonical_concepts.key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_key', 'to_key', 'kind', name='uq_concept_relationships_edge')
    )
    op.create_index(op.f('ix_concept_relationships_from_key'), 'concept_relationships', ['from_key'], unique=False)
    op.create_index(op.f('ix_concept_relationships_to_key'), 'concept_relationships', ['to_key'], unique=False)
    op.create_table('tenant_industry_packs',
    sa.Column('pack_key', sa.String(length=80), nullable=False),
    sa.Column('enabled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['pack_key'], ['industry_packs.key'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'pack_key', name='uq_tenant_industry_packs')
    )
    op.create_index(op.f('ix_tenant_industry_packs_pack_key'), 'tenant_industry_packs', ['pack_key'], unique=False)
    op.create_index(op.f('ix_tenant_industry_packs_tenant_id'), 'tenant_industry_packs', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_chunks_embedding_hnsw'), table_name='chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_chunks_text_fts'), table_name='chunks', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chunks_text_fts'), 'chunks', [sa.literal_column("to_tsvector('english'::regconfig, text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_chunks_embedding_hnsw'), 'chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_tenant_industry_packs_tenant_id'), table_name='tenant_industry_packs')
    op.drop_index(op.f('ix_tenant_industry_packs_pack_key'), table_name='tenant_industry_packs')
    op.drop_table('tenant_industry_packs')
    op.drop_index(op.f('ix_concept_relationships_to_key'), table_name='concept_relationships')
    op.drop_index(op.f('ix_concept_relationships_from_key'), table_name='concept_relationships')
    op.drop_table('concept_relationships')
    op.drop_index(op.f('ix_industry_packs_key'), table_name='industry_packs')
    op.drop_table('industry_packs')
    # ### end Alembic commands ###