"""anomaly detectors and anomalies

Revision ID: 361bdfba719b
Revises: 2515c7d89996
Create Date: 2026-09-26 09:13:03.307943

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '361bdfba719b'
down_revision: str | None = '2515c7d89996'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_detector_definitions',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=60), nullable=False),
    sa.Column('value_concept', sa.String(length=120), nullable=False),
    sa.Column('group_by_concept', sa.String(length=120), nullable=True),
    sa.Column('detector', sa.String(length=30), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('time_basis_preference', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('owner_pack', sa.String(length=80), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_detector_definitions_domain'), 'anomaly_detector_definitions', ['domain'], unique=False)
    op.create_index(op.f('ix_anomaly_detector_definitions_key'), 'anomaly_detector_definitions', ['key'], unique=True)
    op.create_index(op.f('ix_anomaly_detector_definitions_owner_pack'), 'anomaly_detector_definitions', ['owner_pack'], unique=False)
    op.create_table('anomalies',
    sa.Column('detector_key', sa.String(length=120), nullable=False),
    sa.Column('source_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('group_key', sa.String(length=500), nullable=True),
    sa.Column('group_label', sa.String(length=500), nullable=True),
    sa.Column('time_basis_used', sa.String(length=20), nullable=False),
    sa.Column('point_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('expected_min', sa.Float(), nullable=True),
    sa.Column('expected_max', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['detector_key'], ['anomaly_detector_definitions.key'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('detector_key', 'tenant_id', 'group_key', 'point_timestamp', name='uq_anomalies_identity')
    )
    op.create_index(op.f('ix_anomalies_detector_key'), 'anomalies', ['detector_key'], unique=False)
    op.create_index(op.f('ix_anomalies_group_key'), 'anomalies', ['group_key'], unique=False)
    op.create_index(op.f('ix_anomalies_point_timestamp'), 'anomalies', ['point_timestamp'], unique=False)
    op.create_index(op.f('ix_anomalies_severity'), 'anomalies', ['severity'], unique=False)
    op.create_index('ix_anomalies_tenant_detected', 'anomalies', ['tenant_id', 'detected_at'], unique=False)
    op.create_index(op.f('ix_anomalies_tenant_id'), 'anomalies', ['tenant_id'], unique=False)
    op.create_index('ix_anomalies_tenant_severity', 'anomalies', ['tenant_id', 'severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_anomalies_tenant_severity', table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_tenant_id'), table_name='anomalies')
    op.drop_index('ix_anomalies_tenant_detected', table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_severity'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_point_timestamp'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_group_key'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_detector_key'), table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index(op.f('ix_anomaly_detector_definitions_owner_pack'), table_name='anomaly_detector_definitions')
    op.drop_index(op.f('ix_anomaly_detector_definitions_key'), table_name='anomaly_detector_definitions')
    op.drop_index(op.f('ix_anomaly_detector_definitions_domain'), table_name='anomaly_detector_definitions')
    op.drop_table('anomaly_detector_definitions')
    # ### end Alembic commands ###