"""user is_system flag

Revision ID: 387d2f062ccc
Revises: a8e31d7c9062
Create Date: 2026-09-26 21:09:23.747621

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '387d2f062ccc'
down_revision: Union[str, None] = 'a8e31d7c9062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('is_system', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('users', 'is_system', server_default=None)
    op.create_index('ix_users_one_system_per_tenant', 'users', ['tenant_id'], unique=True, postgresql_where=sa.text('is_system = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_one_system_per_tenant', table_name='users', postgresql_where=sa.text('is_system = true'))
    op.drop_column('users', 'is_system')
    # ### end Alembic commands ###