"""canonical concepts and semantic mappings

Revision ID: 3c9c36f3bee2
Revises: 2a7c9e4d1f30
Create Date: 2026-09-21 12:34:46.755495

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa


revision: str = '3c9c36f3bee2'
down_revision: str | None = '2a7c9e4d1f30'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.ForeignKeyConstraint(
        ["canonical_concept_key"], ["canonical_concepts.key"],
        name="fk_semantic_mappings_canonical_concept",
        ondelete="RESTRICT"
)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.UniqueConstraint(
        "source_id", "source_column",
        name="uq_semantic_mappings_source_column",
)
    # ### end Alembic commands ###