"""agent jobs and pending file uploads

Revision ID: 66ec3e4a1e3f
Revises: c5b8d0a7312e
Create Date: 2026-10-03 08:12:49.840659

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '66ec3e4a1e3f'
down_revision: str | None = 'c5b8d0a7312e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_jobs',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=40), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_jobs_agent_id'), 'agent_jobs', ['agent_id'], unique=False)
    op.create_index('ix_agent_jobs_agent_status', 'agent_jobs', ['agent_id', 'status'], unique=False)
    op.create_index(op.f('ix_agent_jobs_job_type'), 'agent_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_agent_jobs_status'), 'agent_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_agent_jobs_tenant_id'), 'agent_jobs', ['tenant_id'], unique=False)
    op.create_table('pending_file_uploads',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('agent_job_id', sa.UUID(), nullable=True),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('expected_hash', sa.String(length=64), nullable=False),
    sa.Column('actual_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_job_id'], ['agent_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['ingestion_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'path', name='uq_pending_file_uploads_job_path')
    )
    op.create_index(op.f('ix_pending_file_uploads_agent_job_id'), 'pending_file_uploads', ['agent_job_id'], unique=False)
    op.create_index(op.f('ix_pending_file_uploads_job_id'), 'pending_file_uploads', ['job_id'], unique=False)
    op.create_index('ix_pending_file_uploads_job_status', 'pending_file_uploads', ['job_id', 'status'], unique=False)
    op.create_index(op.f('ix_pending_file_uploads_status'), 'pending_file_uploads', ['status'], unique=False)
    op.create_index(op.f('ix_pending_file_uploads_tenant_id'), 'pending_file_uploads', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_file_uploads_tenant_id'), table_name='pending_file_uploads')
    op.drop_index(op.f('ix_pending_file_uploads_status'), table_name='pending_file_uploads')
    op.drop_index('ix_pending_file_uploads_job_status', table_name='pending_file_uploads')
    op.drop_index(op.f('ix_pending_file_uploads_job_id'), table_name='pending_file_uploads')
    op.drop_index(op.f('ix_pending_file_uploads_agent_job_id'), table_name='pending_file_uploads')
    op.drop_table('pending_file_uploads')
    op.drop_index(op.f('ix_agent_jobs_tenant_id'), table_name='agent_jobs')
    op.drop_index(op.f('ix_agent_jobs_status'), table_name='agent_jobs')
    op.drop_index(op.f('ix_agent_jobs_job_type'), table_name='agent_jobs')
    op.drop_index('ix_agent_jobs_agent_status', table_name='agent_jobs')
    op.drop_index(op.f('ix_agent_jobs_agent_id'), table_name='agent_jobs')
    op.drop_table('agent_jobs')
    # ### end Alembic commands ###