"""tenant tool policies

Revision ID: 7444df147497
Revises: 194a20299539
Create Date: 2026-09-26 15:29:09.716996

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7444df147497'
down_revision: str | None = '194a20299539'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_tool_policies',
    sa.Column('tool_name', sa.String(length=120), nullable=False),
    sa.Column('policy_override', sa.String(length=20), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'tool_name', name='uq_tenant_tool_policies')
    )
    op.create_index(op.f('ix_tenant_tool_policies_tenant_id'), 'tenant_tool_policies', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tenant_tool_policies_tool_name'), 'tenant_tool_policies', ['tool_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_tool_policies_tool_name'), table_name='tenant_tool_policies')
    op.drop_index(op.f('ix_tenant_tool_policies_tenant_id'), table_name='tenant_tool_policies')
    op.drop_table('tenant_tool_policies')
    # ### end Alembic commands ###