"""webhook deliveries and webhook source fields

Revision ID: 76222380cd3d
Revises: d6dd0b06bb44
Create Date: 2026-09-20 20:19:39.889789

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '76222380cd3d'
down_revision: str | None = 'd6dd0b06bb44'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_deliveries',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_body', sa.LargeBinary(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['ingestion_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_deliveries_job_id'), 'webhook_deliveries', ['job_id'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_source_id'), 'webhook_deliveries', ['source_id'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_status'), 'webhook_deliveries', ['status'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_tenant_id'), 'webhook_deliveries', ['tenant_id'], unique=False)
    op.add_column('data_sources', sa.Column('webhook_token_hash', sa.String(length=64), nullable=True))
    op.add_column('data_sources', sa.Column('webhook_secret_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_data_sources_webhook_token_hash'), 'data_sources', ['webhook_token_hash'], unique=True)
    op.alter_column("data_sources", "webhook_secret_hash", new_column_name="webhook_secret_encrypted", type_=sa.Text())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_sources_webhook_token_hash'), table_name='data_sources')
    op.drop_column('data_sources', 'webhook_secret_encrypted')
    op.drop_column('data_sources', 'webhook_token_hash')
    op.drop_index(op.f('ix_webhook_deliveries_tenant_id'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_status'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_source_id'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_job_id'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    # ### end Alembic commands ###