"""forecasts

Revision ID: 8c775136a9c6
Revises: 361bdfba719b
Create Date: 2026-09-26 10:03:32.227425

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8c775136a9c6'
down_revision: str | None = '361bdfba719b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecasts',
    sa.Column('value_concept', sa.String(length=120), nullable=False),
    sa.Column('group_key', sa.String(length=500), nullable=False),
    sa.Column('group_label', sa.String(length=500), nullable=False),
    sa.Column('source_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('horizon', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('has_seasonality', sa.Boolean(), nullable=False),
    sa.Column('seasonality_period', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(length=40), nullable=True),
    sa.Column('candidates_evaluated', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evaluation_metric', sa.String(length=20), nullable=False),
    sa.Column('validation_error', sa.Float(), nullable=True),
    sa.Column('predicted_points', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('lower_bound', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('upper_bound', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reliability', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_forecasts_tenant_concept', 'forecasts', ['tenant_id', 'value_concept'], unique=False)
    op.create_index(op.f('ix_forecasts_tenant_id'), 'forecasts', ['tenant_id'], unique=False)
    op.create_index('ix_forecasts_tenant_trained', 'forecasts', ['tenant_id', 'trained_at'], unique=False)
    op.create_index(op.f('ix_forecasts_value_concept'), 'forecasts', ['value_concept'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forecasts_value_concept'), table_name='forecasts')
    op.drop_index('ix_forecasts_tenant_trained', table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_tenant_id'), table_name='forecasts')
    op.drop_index('ix_forecasts_tenant_concept', table_name='forecasts')
    op.drop_table('forecasts')
    # ### end Alembic commands ###