"""decision runs

Revision ID: a42596b08551
Revises: 8c775136a9c6
Create Date: 2026-09-26 11:30:08.330976

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a42596b08551'
down_revision: str | None = '8c775136a9c6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_runs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('domain_hint', sa.String(length=60), nullable=True),
    sa.Column('source_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('intent', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('llm_provider', sa.String(length=40), nullable=True),
    sa.Column('llm_model', sa.String(length=120), nullable=True),
    sa.Column('llm_summary', sa.Text(), nullable=True),
    sa.Column('llm_claims', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('llm_recommended_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('llm_tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validated_claims', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dropped_claims', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_runs_tenant_id'), 'decision_runs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_decision_runs_user_id'), 'decision_runs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_runs_user_id'), table_name='decision_runs')
    op.drop_index(op.f('ix_decision_runs_tenant_id'), table_name='decision_runs')
    op.drop_table('decision_runs')
    # ### end Alembic commands ###