"""add event actor kind

Revision ID: a9c26dfd3f18
Revises: 064be53bf059
Create Date: 2026-09-27 08:59:25.164164

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a9c26dfd3f18'
down_revision: str | None = '064be53bf059'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'events',
        sa.Column(
            'actor_kind',
            sa.String(length=20),
            nullable=False,
            server_default='system',
        ),
    )
    op.alter_column('events', 'actor_kind', server_default=None)
    op.create_index(op.f('ix_events_actor_kind'), 'events', ['actor_kind'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_actor_kind'), table_name='events')
    op.drop_column('events', 'actor_kind')
    # ### end Alembic commands ###