"""workflow instance idempotency key

Revision ID: aff65a1049f9
Revises: b7a1f2c9d4e6
Create Date: 2026-10-01 19:04:45.923793

"""
from __future__ import annotations

from collections.abc import Sequence



revision: str = 'aff65a1049f9'
down_revision: str | None = 'b7a1f2c9d4e6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###