"""kpi definitions

Revision ID: c1f13925c77a
Revises: 3421a29ec851
Create Date: 2026-09-23 19:37:27.704365

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c1f13925c77a'
down_revision: str | None = '3421a29ec851'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpi_definitions',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=60), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('formula', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('owner_pack', sa.String(length=80), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kpi_definitions_domain'), 'kpi_definitions', ['domain'], unique=False)
    op.create_index(op.f('ix_kpi_definitions_key'), 'kpi_definitions', ['key'], unique=True)
    op.create_index(op.f('ix_kpi_definitions_owner_pack'), 'kpi_definitions', ['owner_pack'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kpi_definitions_owner_pack'), table_name='kpi_definitions')
    op.drop_index(op.f('ix_kpi_definitions_key'), table_name='kpi_definitions')
    op.drop_index(op.f('ix_kpi_definitions_domain'), table_name='kpi_definitions')
    op.drop_table('kpi_definitions')
    # ### end Alembic commands ###