"""workflow instances

Revision ID: c371f6253ad0
Revises: 7444df147497
Create Date: 2026-09-26 16:15:45.969407

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c371f6253ad0'
down_revision: str | None = '7444df147497'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_instances',
    sa.Column('workflow_key', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_step', sa.String(length=120), nullable=True),
    sa.Column('step_states', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('workflow_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('triggered_by_user_id', sa.UUID(), nullable=True),
    sa.Column('trigger_type', sa.String(length=40), nullable=False),
    sa.Column('trigger_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decision_run_id', sa.UUID(), nullable=True),
    sa.Column('pending_approval_step', sa.String(length=120), nullable=True),
    sa.Column('pending_action_id', sa.UUID(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['decision_run_id'], ['decision_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pending_action_id'], ['action_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_instances_decision_run_id'), 'workflow_instances', ['decision_run_id'], unique=False)
    op.create_index(op.f('ix_workflow_instances_pending_action_id'), 'workflow_instances', ['pending_action_id'], unique=False)
    op.create_index(op.f('ix_workflow_instances_status'), 'workflow_instances', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_instances_tenant_id'), 'workflow_instances', ['tenant_id'], unique=False)
    op.create_index('ix_workflow_instances_tenant_status', 'workflow_instances', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_workflow_instances_workflow_key'), 'workflow_instances', ['workflow_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_instances_workflow_key'), table_name='workflow_instances')
    op.drop_index('ix_workflow_instances_tenant_status', table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_tenant_id'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_status'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_pending_action_id'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_decision_run_id'), table_name='workflow_instances')
    op.drop_table('workflow_instances')
    # ### end Alembic commands ###