"""canonical concepts and semantic mappings

Revision ID: d6dd0b06bb44
Revises: e55b5bd5e1e0
Create Date: 2026-09-19 17:26:37.597009

"""
from __future__ import annotations

from collections.abc import Sequence



revision: str = 'd6dd0b06bb44'
down_revision: str | None = 'e55b5bd5e1e0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###