"""data profile

Revision ID: d87dd373e037
Revises: 1b83d1dab5ef
Create Date: 2026-09-19 15:31:14.812858

"""
from __future__ import annotations

from collections.abc import Sequence

revision: str = 'd87dd373e037'
down_revision: str | None = '1b83d1dab5ef'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###