"""canonical concepts and semantic mappings

Revision ID: e55b5bd5e1e0
Revises: d87dd373e037
Create Date: 2026-09-19 17:15:30.117345

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e55b5bd5e1e0'
down_revision: str | None = 'd87dd373e037'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_concepts',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=60), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('synonyms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canonical_concepts_domain'), 'canonical_concepts', ['domain'], unique=False)
    op.create_index(op.f('ix_canonical_concepts_key'), 'canonical_concepts', ['key'], unique=True)
    op.create_table('semantic_mappings',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('source_column', sa.String(length=200), nullable=False),
    sa.Column('canonical_concept_key', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('rationale', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confirmed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['canonical_concept_key'], ['canonical_concepts.key'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['confirmed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'source_column', name='uq_semantic_mappings_source_column')
    )
    op.create_index(op.f('ix_semantic_mappings_canonical_concept_key'), 'semantic_mappings', ['canonical_concept_key'], unique=False)
    op.create_index(op.f('ix_semantic_mappings_source_id'), 'semantic_mappings', ['source_id'], unique=False)
    op.create_index(op.f('ix_semantic_mappings_status'), 'semantic_mappings', ['status'], unique=False)
    op.create_index(op.f('ix_semantic_mappings_tenant_id'), 'semantic_mappings', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_semantic_mappings_tenant_id'), table_name='semantic_mappings')
    op.drop_index(op.f('ix_semantic_mappings_status'), table_name='semantic_mappings')
    op.drop_index(op.f('ix_semantic_mappings_source_id'), table_name='semantic_mappings')
    op.drop_index(op.f('ix_semantic_mappings_canonical_concept_key'), table_name='semantic_mappings')
    op.drop_table('semantic_mappings')
    op.drop_index(op.f('ix_canonical_concepts_key'), table_name='canonical_concepts')
    op.drop_index(op.f('ix_canonical_concepts_domain'), table_name='canonical_concepts')
    op.drop_table('canonical_concepts')
    # ### end Alembic commands ###