"""add email oauth state

Revision ID: f4f0ba164e82
Revises: f91f84c35bc9
Create Date: 2026-10-10 10:22:56.670574

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f4f0ba164e82'
down_revision: str | None = 'f91f84c35bc9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_oauth_states',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('state_hash', sa.String(length=64), nullable=False),
    sa.Column('redirect_uri', sa.String(length=500), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_oauth_states_expires_at'), 'email_oauth_states', ['expires_at'], unique=False)
    op.create_index(op.f('ix_email_oauth_states_source_id'), 'email_oauth_states', ['source_id'], unique=False)
    op.create_index(op.f('ix_email_oauth_states_state_hash'), 'email_oauth_states', ['state_hash'], unique=True)
    op.create_index(op.f('ix_email_oauth_states_status'), 'email_oauth_states', ['status'], unique=False)
    op.create_index(op.f('ix_email_oauth_states_tenant_id'), 'email_oauth_states', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_email_oauth_states_user_id'), 'email_oauth_states', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_oauth_states_user_id'), table_name='email_oauth_states')
    op.drop_index(op.f('ix_email_oauth_states_tenant_id'), table_name='email_oauth_states')
    op.drop_index(op.f('ix_email_oauth_states_status'), table_name='email_oauth_states')
    op.drop_index(op.f('ix_email_oauth_states_state_hash'), table_name='email_oauth_states')
    op.drop_index(op.f('ix_email_oauth_states_source_id'), table_name='email_oauth_states')
    op.drop_index(op.f('ix_email_oauth_states_expires_at'), table_name='email_oauth_states')
    op.drop_table('email_oauth_states')
    # ### end Alembic commands ###