"""add email accounts

Revision ID: f91f84c35bc9
Revises: e73b5190a4c2
Create Date: 2026-10-05 21:57:20.705413

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "f91f84c35bc9"
down_revision: str | None = "e73b5190a4c2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_accounts",
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("email_address", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("oauth_tokens_encrypted", sa.Text(), nullable=True),
        sa.Column("sync_cursor", sa.String(length=500), nullable=True),
        sa.Column("sync_cursor_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("connected_by_user_id", sa.UUID(), nullable=True),
        sa.Column("account_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["connected_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_id"], ["data_sources.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "email_address", name="uq_email_accounts_tenant_address"),
    )
    op.create_index(
        op.f("ix_email_accounts_email_address"), "email_accounts", ["email_address"], unique=False
    )
    op.create_index(
        op.f("ix_email_accounts_last_sync_at"), "email_accounts", ["last_sync_at"], unique=False
    )
    op.create_index(
        op.f("ix_email_accounts_provider"), "email_accounts", ["provider"], unique=False
    )
    op.create_index(
        op.f("ix_email_accounts_source_id"), "email_accounts", ["source_id"], unique=False
    )
    op.create_index(op.f("ix_email_accounts_status"), "email_accounts", ["status"], unique=False)
    op.create_index(
        op.f("ix_email_accounts_tenant_id"), "email_accounts", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_email_accounts_tenant_status", "email_accounts", ["tenant_id", "status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_email_accounts_tenant_status", table_name="email_accounts")
    op.drop_index(op.f("ix_email_accounts_tenant_id"), table_name="email_accounts")
    op.drop_index(op.f("ix_email_accounts_status"), table_name="email_accounts")
    op.drop_index(op.f("ix_email_accounts_source_id"), table_name="email_accounts")
    op.drop_index(op.f("ix_email_accounts_provider"), table_name="email_accounts")
    op.drop_index(op.f("ix_email_accounts_last_sync_at"), table_name="email_accounts")
    op.drop_index(op.f("ix_email_accounts_email_address"), table_name="email_accounts")
    op.drop_table("email_accounts")
    # ### end Alembic commands ###
