"""action records

Revision ID: f9ec2467ce29
Revises: a42596b08551
Create Date: 2026-09-26 13:12:47.788984

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f9ec2467ce29'
down_revision: str | None = 'a42596b08551'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_records',
    sa.Column('decision_run_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=120), nullable=False),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('validation_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('execution_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('proposed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['decision_run_id'], ['decision_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_records_decision_run_id'), 'action_records', ['decision_run_id'], unique=False)
    op.create_index(op.f('ix_action_records_status'), 'action_records', ['status'], unique=False)
    op.create_index(op.f('ix_action_records_tenant_id'), 'action_records', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_action_records_tool_name'), 'action_records', ['tool_name'], unique=False)
    op.create_index(op.f('ix_action_records_user_id'), 'action_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_records_user_id'), table_name='action_records')
    op.drop_index(op.f('ix_action_records_tool_name'), table_name='action_records')
    op.drop_index(op.f('ix_action_records_tenant_id'), table_name='action_records')
    op.drop_index(op.f('ix_action_records_status'), table_name='action_records')
    op.drop_index(op.f('ix_action_records_decision_run_id'), table_name='action_records')
    op.drop_table('action_records')
    # ### end Alembic commands ###